@Observed
export class GetChannelUser{
  batteryType?: string
  batteryTypeName?: string
  bindBatteryBid?: string
  bindBatterySn?: string
  canRecycleGoldBeanNum?: number
  realNameStatus?: number
  channelMid?: string
  depositAmount?: number
  userChannelStatus?: number
  depositFlag?: number
  depositOrderId?: number
  nickName?: string
  packageAmount?: number
  packageFinishTime?: string
  packageOrderId?: number
  packageStartTime?: string
  remainDays?: number
  userId?: number
  userPhone?: string
  userRemark?: string
}
